name: Build and Release Workflow

on:
  workflow_run:
    workflows: ["run Tests"]
    types:
      - completed
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Configure git user
        run: |
          git config --global user.email "GHActions@demifinance.com"
          git config --global user.name "GH Runner"

      - name: Increment version and tag
        id: version
        run: |
          NEW_VERSION=$(npm version patch -m "Upgrade to %s for reasons")
          echo "::set-output name=new_tag::$NEW_VERSION"
          git push --follow-tags

      - name: Run archive
        run: npm run build:archive

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.new_tag }}
          release_name: Release ${{ steps.version.outputs.new_tag }}
          draft: false
          prerelease: false
