name: Deployment Latest Release Workflow

on:
  workflow_run:
    workflows: ["Build and Release Workflow"]
    types:
      - completed
    branches:
      - main


jobs:
  deploy:
    runs-on: self-hosted # Ensure this matches the label of your self-hosted runner
    steps:
      - name: Download Source Code Archive
        run: |
          curl -sL -o source-code.tar.gz $(curl -sH "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/DemiFinance/DemiApi/releases/latest" | jq -r ".tarball_url")

      - name: Create extraction directory
        run: mkdir -p extractedRelease

      - name: Extract the Source Code Archive
        run: tar -xzvf source-code.tar.gz -C extractedRelease

      - name: Extract Nested build.tar.gz
        run: tar -xzvf extractedRelease/build.tar.gz -C .

      - name: Install dependencies
        run: npm ci

      - name: Start or Reload application using PM2
        run: pm2 reload all || pm2 start doppler-run.sh --name demi-api
        env:
          NODE_ENV: production
