name: Deployment Latest Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: self-hosted # Ensure this matches the label of your self-hosted runner
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Download Release Asset
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
          path: path/to/download

      - name: Extract the Release Archive
        run: tar -xzvf path/to/download/release.tar.gz -C path/to/release/extracted/

      - name: Extract Nested build.tar.gz
        run: tar -xzvf path/to/release/extracted/build.tar.gz -C path/to/final/destination/

      - name: Install dependencies
        run: npm ci
        working-directory: path/to/final/destination/

      - name: Run custom npm command
        run: npm run custom-command # Replace 'custom-command' with your specific npm command
        working-directory: path/to/final/destination/

      - name: Start or Reload application using PM2
        run: pm2 reload all || pm2 start path/to/final/destination/app.js --name your-app-name
        env:
          NODE_ENV: production
