name: Deployment Latest Release Workflow

on:
  workflow_run:
    workflows: ["Build and Release Workflow"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted # Ensure this targets your self-hosted runner with Docker installed

    steps:
      - name: Ensure runner user has proper permissions
        run: sudo chown -R $(whoami):$(whoami) . && sudo chmod -R 755 .

      - name: Download Docker Image from Release Asset
        run: |
          ASSET_URL=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | \
            grep "browser_download_url.*demidocker.tar" | \
            cut -d '"' -f 4)
          wget -O demidocker.tar "${ASSET_URL}" --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}'

      - name: Load Docker Image
        run: |
         sudo docker load -i demidocker.tar

      - name: Stop Existing Container
        run: |
          sudo docker stop demidocker || true
          docker rm demidocker || true

      - name: Run Docker Container
        run: |
         sudo docker run -d --name demidocker -p 8080:8080 demidocker # Replace `your_image_name` and ports as needed


