name: Deployment Latest Release Workflow

on:
  release:
    types: [created, published, edited, released]

jobs:
  deploy:
    runs-on: self-hosted # Ensure this matches the label of your self-hosted runner
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Get latest release
        id: get-latest-release
        run: |
          curl -sH "Accept: application/vnd.github.v3+json" https://api.github.com/repos/DemiFinance/DemiApi/releases/latest | 
          jq -r ".tarball_url" > $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Source Code Archive
        run: curl -sL -o source-code.tar.gz $(cat $GITHUB_ENV)

      - name: Extract the Source Code Archive
        run: tar -xzvf source-code.tar.gz -C .

      - name: Extract Nested build.tar.gz
        run: tar -xzvf DemiApi-*-build.tar.gz -C .

      - name: Install dependencies
        run: npm ci

      - name: Start or Reload application using PM2
        run: pm2 reload all || pm2 start doppler-run.sh --name demi-api
        env:
          NODE_ENV: production
