name: run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present

    - name: Export Environment Variables
      run: |
        echo "export DD_API_KEY=${{ secrets.DD_API_KEY }}" >> $GITHUB_ENV
        echo "export DD_APP_KEY=${{ secrets.DD_APP_KEY }}" >> $GITHUB_ENV
        echo "export DD_CIVISIBILITY_AGENTLESS_ENABLED=true" >> $GITHUB_ENV
        echo "export DD_SITE=datadoghq.com" >> $GITHUB_ENV

    - name: Run Tests
      run: |
        source $GITHUB_ENV
        npm test
